-- Auto-generated registry seed: canon sigils + signs from data/sigils.json & data/signs.json.
-- Regenerate via the inline node script in the SPEC/WS3 step. operator_kind left null for sigils;
-- for signs we stash the doc family as a hint (real grammar operator_kind can be backfilled later).
insert into public.symbols (kind, name, label, engine_id, status, operator_kind) values
('sigil', 'fire', 'Fire', 'fire', 'canon', null),
('sigil', 'water', 'Water', 'water', 'canon', null),
('sigil', 'earth', 'Earth', 'earth', 'canon', null),
('sigil', 'wind', 'Wind', 'wind', 'canon', null),
('sigil', 'light', 'Light', 'light', 'canon', null),
('sigil', 'wind_underfoot', 'Wind Underfoot', 'wind_underfoot', 'canon', null),
('sigil', 'aeriforms', 'Aeriforms', 'aeriforms', 'canon', null),
('sigil', 'whorling_wind', 'Whorling Winds', 'whorling_wind', 'canon', null),
('sigil', 'crystal', 'Crystal', 'crystal', 'canon', null),
('sigil', 'repetition_sigil', 'Repetition', 'repetition_sigil', 'canon', null),
('sigil', 'vision_sigil', 'Vision (as sigil)', 'vision_sigil', 'canon', null),
('sigil', 'billowing_sigil', 'Billowing (as sigil)', 'billowing_sigil', 'canon', null),
('sigil', 'unknown_sigil', 'Unknown / Forbidden Sigil', 'unknown_sigil', 'canon', null),
('sigil', 'unburning_flame', 'Unburning Flames', 'unburning_flame', 'canon', null),
('sigil', 'stop', 'Stop', 'stop', 'canon', null),
('sigil', 'bird_a', 'Bird A', 'bird_a', 'canon', null),
('sigil', 'bird_b', 'Bird B', 'bird_b', 'canon', null),
('sigil', 'dragon', 'Dragon', 'dragon', 'canon', null),
('sigil', 'flower', 'Flower', 'flower', 'canon', null),
('sigil', 'flower_water', 'Water Flower', 'flower_water', 'canon', null),
('sigil', 'horse', 'Horse', 'horse', 'canon', null),
('sigil', 'owlcat', 'Owlcat', 'owlcat', 'canon', null),
('sigil', 'owlcat_head', 'Owlcat Head', 'owlcat_head', 'canon', null),
('sigil', 'scalewolf', 'Scalewolf', 'scalewolf', 'canon', null),
('sigil', 'torchstag', 'Torchstag', 'torchstag', 'canon', null),
('sigil', 'liongoat', 'Liongoat', 'liongoat', 'canon', null),
('sigil', 'valance_leech', 'Valance Leech', 'valance_leech', 'canon', null),
('sigil', 'sword', 'Sword', 'sword', 'canon', null),
('sigil', 'smoke', 'Smoke', 'smoke', 'canon', null),
('sigil', 'guidance', 'Guidance', 'guidance', 'canon', null),
('sigil', 'calling', 'Calling', 'calling', 'canon', null),
('sigil', 'sand_bridge', 'Sand Bridge Sigil', 'sand_bridge', 'canon', null),
('sigil', 'warding_pillar', 'Warding Pillar (Beast-Ward Staff)', 'warding_pillar', 'canon', null),
('sign', 'column', 'Column', 'column', 'canon', 'directional'),
('sign', 'dispersion', 'Dispersion', 'dispersion', 'canon', 'directional'),
('sign', 'levitation', 'Levitation', 'levitation', 'canon', 'directional'),
('sign', 'pull', 'Pull', 'pull', 'canon', 'directional'),
('sign', 'crush', 'Crush', 'crush', 'canon', 'semi-directional'),
('sign', 'float', 'Float', 'float', 'canon', 'non-directional'),
('sign', 'direction', 'Region', 'direction', 'canon', 'directional'),
('sign', 'convergence', 'Convergence', 'convergence', 'canon', 'semi-directional'),
('sign', 'diamond', 'Diamond', 'diamond', 'canon', 'non-directional'),
('sign', 'window', 'Window', 'window', 'canon', 'non-directional'),
('sign', 'collection', 'Collection', 'collection', 'canon', 'directional'),
('sign', 'crosshair', 'Crosshair', 'crosshair', 'canon', 'non-directional'),
('sign', 'radial', 'Radial', 'radial', 'canon', 'semi-directional'),
('sign', 'bolt', 'Bolt', 'bolt', 'canon', 'non-directional'),
('sign', 'billowing', 'Billow', 'billowing', 'canon', 'non-directional'),
('sign', 'eye', 'Eye', 'eye', 'canon', 'non-directional'),
('sign', 'bend', 'Bend', 'bend', 'canon', 'non-directional'),
('sign', 'repetition', 'Repetition', 'repetition', 'canon', 'non-directional'),
('sign', 'vision', 'Vision', 'vision', 'canon', 'non-directional'),
('sign', 'weave', 'Weave', 'weave', 'canon', 'semi-directional'),
('sign', 'enlarge', 'Enlarge', 'enlarge', 'canon', 'semi-directional'),
('sign', 'rain', 'Rain', 'rain', 'canon', 'semi-directional'),
('sign', 'bird', 'Bird', 'bird', 'canon', null),
('sign', 'dancing_puppet', 'Puppet', 'dancing_puppet', 'canon', 'semi-directional'),
('sign', 'animal_signs', 'Animal Signs', 'animal_signs', 'canon', null),
('sign', 'unknown_sign', 'Unknown Sign', 'unknown_sign', 'canon', null),
('sign', 'unknown_01', 'Unknown Sign 1', 'unknown_01', 'canon', 'unknown'),
('sign', 'unknown_02', 'Unknown Sign 2', 'unknown_02', 'canon', 'unknown'),
('sign', 'unknown_03', 'Unknown Sign 3', 'unknown_03', 'canon', 'unknown'),
('sign', 'unknown_04', 'Unknown Sign 4', 'unknown_04', 'canon', 'unknown'),
('sign', 'unknown_05', 'Unknown Sign 5', 'unknown_05', 'canon', 'unknown'),
('sign', 'unknown_07', 'Unknown Sign 7', 'unknown_07', 'canon', 'unknown'),
('sign', 'unknown_08', 'Unknown Sign 8', 'unknown_08', 'canon', 'unknown'),
('sign', 'sights_set', 'Sights Set', 'sights_set', 'canon', 'directional'),
('sign', 'gather', 'Gather', 'gather', 'canon', 'directional'),
('sign', 'strengthen', 'Strengthen', 'strengthen', 'canon', 'semi-directional'),
('sign', 'entwine', 'Entwine', 'entwine', 'canon', 'semi-directional'),
('sign', 'aeriforms_defined', 'Aeriforms Defined', 'aeriforms_defined', 'canon', 'semi-directional'),
('sign', 'glaives', 'Glaives', 'glaives', 'canon', 'semi-directional'),
('sign', 'bind', 'Bind', 'bind', 'canon', 'semi-directional'),
('sign', 'link', 'Link', 'link', 'canon', 'semi-directional'),
('sign', 'cool', 'Cool', 'cool', 'canon', 'non-directional'),
('sign', 'orb', 'Orb', 'orb', 'canon', 'non-directional'),
('sign', 'sign_of_wind', 'Sign of Wind', 'sign_of_wind', 'canon', 'asymmetric'),
('sign', 'purify', 'Purify', 'purify', 'canon', 'asymmetric'),
('sign', 'solidification', 'Solidification', 'solidification', 'canon', 'semi-directional'),
('sign', 'envelopment', 'Envelopment', 'envelopment', 'canon', 'semi-directional'),
('sign', 'unknown_06', 'Unknown Sign 6', 'unknown_06', 'canon', 'unknown'),
('sign', 'unknown_09', 'Unknown Sign 9', 'unknown_09', 'canon', 'unknown'),
('sign', 'unknown_10', 'Unknown Sign 10', 'unknown_10', 'canon', 'unknown'),
('sign', 'unknown_11', 'Unknown Sign 11', 'unknown_11', 'canon', 'unknown'),
('sign', 'unknown_12', 'Unknown Sign 12 (Beast-Ward Cross)', 'unknown_12', 'canon', 'unknown')
on conflict (name) do nothing;
