// seedTemplates.js — the hardcoded, bundled training set for the web prototype.
//
// Mirrors what data-services/samples.js#activeTemplates produced from the database, but reads the
// static snapshot (data/training-seed.json, generated by tools/build-training-seed.mjs) instead.
// This is the ONLY training source on the web build: no localStorage, no DB, identical for every
// visitor. See docs/app/SPEC-web-prototype.md §3.
//
// Each returned template: { name, role, points, source, weight } — the shape the $P recognizer expects.

import seed from '../../../data/training-seed.json'
import rules from '../../../data/rules.json'

const DEFAULT_SAMPLE_WEIGHTS = { corrected: 1.5, drawn: 1.0, confirmed: 0.6 }

export function seedTemplates() {
  const sampleWeights = rules.recognition?.sampleWeights ?? DEFAULT_SAMPLE_WEIGHTS
  return seed.map((s) => ({
    name: s.name,
    role: s.role,
    points: s.points,
    source: s.source,
    weight: sampleWeights[s.source] ?? 1.0,
  }))
}
